from collections.abc import Mapping, Sequence
from typing import Any, TypedDict, final
import numpy as np


class RuntimeInfo(TypedDict):
    device_type: str
    device_id: int


__version__: str


def runtime_info() -> RuntimeInfo: ...


@final
class Instance:
    def __init__(self, vendor: str, *, device_ids: Sequence[int] = (0,), default_device_id: int = 0) -> None: ...
    @property
    def vendor(self) -> str: ...
    @property
    def default_device(self) -> Device: ...
    def device(self, id: int) -> Device: ...
    def flush(self) -> None: ...


@final
class Device:
    @property
    def id(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def instance(self) -> Instance: ...
    def flush(self) -> None: ...


_primitive_types: Mapping[str, int]


@final
class Tensor:
    @property
    def device(self) -> Device: ...
    @property
    def dtype(self) -> np.dtype[Any]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def strides(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...


def _to_device(device: Device, host: object, primitive_type: int, shape: Sequence[int]) -> Tensor: ...
def _to_host(tensor: Tensor) -> np.ndarray[Any, Any]: ...
def _invoke_builtin(device: Device, name: str, operands: tuple[object, ...]) -> object: ...
