[package]
name = "tofu"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../crates/tofu-core" }
syntax = { path = "../crates/tofu-syntax" }
sema = { path = "../crates/tofu-sema" }
driver = { path = "../crates/tofu-driver" }


rustyline = "17.0.2"
miette = {version= "7.6.0", features = ["fancy"]}
rustyline-derive = "0.11.1"
logos = "0.16.0"
clap = {version="4.5.54", features=["derive"]}
