[package]
name = "kuai"
version = "0.1.0"
edition = "2024"

[dependencies]
syntax = { path = "../crates/kuai-syntax" }
sema = { path = "../crates/kuai-sema" }
driver = { path = "../crates/kuai-driver" }

rustyline = "17.0.2"
miette = {version= "7.6.0", features = ["fancy"]}
thiserror = "2.0.17"
rustyline-derive = "0.11.1"
logos = "0.16.0"
clap = {version="4.5.54", features=["derive"]}
