[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "kupy"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy"]

[tool.scikit-build]
cmake.source-dir = "."
wheel.packages = ["src/kupy"]
build-dir="build"

[tool.scikit-build.cmake.define]
CMAKE_EXPORT_COMPILE_COMMANDS = "ON"
